[package]
name = "ddsaveedit"
version = "0.1.0"
authors = ["robojumper <robojumper@gmail.com>"]
edition = "2018"

[dependencies]
ddsavelib = { path = "../ddsavelib" }

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "load_save"
harness = false
test = true
